name: eileen
channels:
  - conda-forge
  - defaults
dependencies:
  - _python_abi3_support=1.0
  - anyio=4.12.0
  - aom=3.12.1
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.4.0
  - asttokens=3.0.1
  - async-lru=2.0.5
  - attrs=25.4.0
  - babel=2.17.0
  - backports.zstd=1.2.0
  - beautifulsoup4=4.14.3
  - blas=1.0
  - bleach=6.3.0
  - bleach-with-css=6.3.0
  - bottleneck=1.4.2
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - certifi=2026.01.04
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.3
  - cpython=3.14.2
  - cycler=0.12.1
  - dav1d=1.2.1
  - debugpy=1.8.19
  - decorator=5.2.1
  - defusedxml=0.7.1
  - exceptiongroup=1.3.1
  - executing=2.2.1
  - expat=2.7.3
  - fontconfig=2.15.0
  - fonttools=4.60.1
  - fqdn=1.5.1
  - freeglut=3.8.0
  - freetype=2.13.3
  - fribidi=1.0.10
  - graphite2=1.3.14
  - h11=0.16.0
  - h2=4.3.0
  - harfbuzz=10.2.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icc_rt=2022.1.0
  - icu=73.1
  - idna=3.11
  - importlib-metadata=8.7.0
  - importlib_resources=6.5.2
  - iniconfig=2.3.0
  - intel-openmp=2025.0.0
  - ipykernel=7.1.0
  - ipython=9.8.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.8
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.2
  - jpeg=9f
  - json5=0.12.1
  - jsonpointer=3.0.0
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.25.1
  - jupyter=1.1.1
  - jupyter-lsp=2.3.0
  - jupyter_client=8.7.0
  - jupyter_console=6.6.3
  - jupyter_core=5.9.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.5.1
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - jupyterlab_widgets=3.0.16
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lark=1.3.1
  - lcms2=2.17
  - lerc=4.0.0
  - libavif=1.3.0
  - libdeflate=1.22
  - libexpat=2.7.3
  - libffi=3.4.4
  - libglib=2.84.4
  - libhwloc=2.12.1
  - libiconv=1.16
  - libkrb5=1.21.3
  - libmpdec=4.0.0
  - libopenjpeg=2.5.4
  - libpng=1.6.50
  - libpq=17.6
  - libsodium=1.0.20
  - libtiff=4.7.1
  - libwebp-base=1.6.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - markupsafe=3.0.3
  - matplotlib=3.10.7
  - matplotlib-base=3.10.7
  - matplotlib-inline=0.2.1
  - mistune=3.2.0
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.1
  - mkl_random=1.3.0
  - mysql-common=9.3.0
  - mysql-libs=9.3.0
  - nbclient=0.10.4
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - notebook=7.5.1
  - notebook-shim=0.2.4
  - numexpr=2.14.1
  - numpy=2.3.5
  - numpy-base=2.3.5
  - openssl=3.6.0
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.3
  - pandocfilters=1.5.0
  - parso=0.8.5
  - pcre2=10.46
  - pillow=12.0.0
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.1
  - pluggy=1.5.0
  - prometheus_client=0.23.1
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - psutil=7.2.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.2
  - pyparsing=3.2.5
  - pyqt=6.9.1
  - pyqt6-sip=13.10.2
  - pysocks=1.7.1
  - pytest=8.4.2
  - python=3.14.2
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-gil=3.14.2
  - python-json-logger=2.0.7
  - python-tzdata=2025.3
  - python_abi=3.14
  - pytz=2025.2
  - pywin32=311
  - pywinpty=2.0.15
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qtbase=6.9.2
  - qtdeclarative=6.9.2
  - qtsvg=6.9.2
  - qttools=6.9.2
  - qtwebchannel=6.9.2
  - qtwebsockets=6.9.2
  - referencing=0.37.0
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rpds-py=0.30.0
  - scipy=1.16.3
  - send2trash=1.8.3
  - setuptools=80.9.0
  - sip=6.12.0
  - six=1.17.0
  - sniffio=1.3.1
  - soupsieve=2.8.1
  - sqlite=3.51.0
  - stack_data=0.6.3
  - tbb=2022.3.0
  - tbb-devel=2022.3.0
  - terminado=0.18.1
  - threadpoolctl=3.5.0
  - tinycss2=1.5.1
  - tk=8.6.15
  - tomli=2.3.0
  - tornado=6.5.4
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - uri-template=1.3.0
  - urllib3=2.6.2
  - vc=14.42
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.14
  - webcolors=25.10.0
  - webencodings=0.5.1
  - websocket-client=1.9.0
  - widgetsnbextension=4.0.15
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - alembic==1.17.2
      - click==8.3.1
      - cloudpickle==3.1.2
      - cmdstanpy==1.3.0
      - colorlog==6.10.1
      - darts==0.40.0
      - filelock==3.20.1
      - frozenlist==1.8.0
      - fsspec==2025.12.0
      - greenlet==3.3.0
      - hf-xet==1.2.0
      - holidays==0.87
      - huggingface-hub==1.2.3
      - lightgbm==4.6.0
      - lightning-utilities==0.15.2
      - llvmlite==0.46.0b1
      - mako==1.3.10
      - mpmath==1.3.0
      - multidict==6.7.0
      - narwhals==2.14.0
      - networkx==3.6.1
      - nfoursid==1.0.2
      - numba==0.63.0b1
      - optuna==4.6.0
      - patsy==1.0.2
      - propcache==0.4.1
      - prophet==1.2.1
      - protobuf==6.33.2
      - pyod==2.0.6
      - pytorch-lightning==2.5.2
      - safetensors==0.7.0
      - scikit-base==0.13.0
      - scikit-learn==1.7.2
      - shap==0.50.0
      - shellingham==1.5.4
      - sktime==0.40.1
      - slicer==0.0.8
      - sqlalchemy==2.0.45
      - stanio==0.5.1
      - statsmodels==0.14.6
      - sympy==1.14.0
      - tensorboardx==2.6.4
      - torch==2.9.1
      - torchmetrics==1.8.2
      - typer-slim==0.20.1
      - xarray==2025.12.0
      - xgboost==3.1.2
      - yarl==1.22.0
